version: "3.9"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "25:25"
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    restart: always
    image: "redis:alpine"
    environment:
      - REDIS_AOF_ENABLED=yes
    ports:
      - "6379:6379"
    volumes:
      - ./redis-volume:/data

  admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
